(run-test "test_string.scm:string "
          (begin
            [assert (string? "abc")  #t]
            [assert (string? #\a)    #f]
            [assert (string? '())    #f]
            [assert (string-length "abc")  3]
            [assert (string-length "")  0]
            [assert (string-length (make-string 8))      8]
            [assert (string-length (make-string 3 #\z))  3]
            [assert (string-ref (make-string 3 #\z) 0)  #\z]
            [assert (string-ref (make-string 3 #\z) 1)  #\z]
            [assert (string-ref (make-string 3 #\z) 2)  #\z]
            [assert (string #\a #\b #\c)  "abc"]
            [assert (string-ref "abc" 0)  #\a ]
            [assert (string-ref "abc" 1)  #\b ]
            [assert (string-ref "abc" 2)  #\c ]
            [assert (let [(str "abc")]
               (string-set! str 1 #\z)
               str)  "azc"]
            [assert (string-copy "aiueo")  "aiueo"]
            [assert (let* ((str1 "abc")(str2 (string-copy str1)))(string-set! str1 1 #\z) str2)  "abc"]
            [assert (string->list "aiueo")  (quote (#\a #\i #\u #\e #\o))]
            [assert (list->string '(#\a #\b #\c))  "abc"]
            [assert (list->string '(#\a))  "a"]
            [assert (let ((str "abc"))(string-fill! str #\z) str)  "zzz"]
            [assert (string-append "abc" "def")  "abcdef"]
            [assert (string-append "" "xyz")  "xyz"]
            [assert (string-append "abc" "" "def")  "abcdef"]
            [assert (string-append "def" "" "ghi")  "defghi"]
            [assert (substring "abcdef" 1 3)  "bc"]
))


(run-test "test_string.scm:string_equivalence "
          (begin
            [assert (string=? "abc" "abc")  #t]
            [assert (string=? "abc" "def")  #f]
            [assert (string=? "abc" "ABC")  #f]

            [assert (string-ci=? "abc" "abc")  #t]
            [assert (string-ci=? "abc" "def")  #f]
            [assert (string-ci=? "abc" "ABC")  #t]

            [assert (string<? "abc" "abd")   #t]
            [assert (string<? "abc" "abc")   #f]
            [assert (string<? "abc" "abcd")  #t]
            [assert (string<? "def" "abc")   #f]

            [assert (string-ci<? "abc" "abd")   #t]
            [assert (string-ci<? "abc" "ABC")   #f]
            [assert (string-ci<? "ABC" "abc")   #f]
            [assert (string-ci<? "abc" "abcd")  #t]
            [assert (string-ci<? "ABC" "abcd")  #t]
            [assert (string-ci<? "abc" "ABCD")  #t]
            [assert (string-ci<? "def" "abc")   #f]
            [assert (string-ci<? "DEF" "abc")   #f]

            [assert (string>? "abc" "abd")   #f]
            [assert (string>? "abc" "abc")   #f]
            [assert (string>? "abc" "abcd")  #f]
            [assert (string>? "def" "abc")   #t]

            [assert (string-ci>? "abc" "abd")   #f]
            [assert (string-ci>? "ABC" "abd")   #f]
            [assert (string-ci>? "abc" "ABD")   #f]
            [assert (string-ci>? "abc" "abc")   #f]
            [assert (string-ci>? "abc" "ABC")   #f]
            [assert (string-ci>? "abc" "abcd")  #f]
            [assert (string-ci>? "ABC" "abcd")  #f]
            [assert (string-ci>? "abc" "ABCD")  #f]
            [assert (string-ci>? "def" "abc")   #t]
            [assert (string-ci>? "DEF" "abc")   #t]
            [assert (string-ci>? "def" "ABC")   #t]

            [assert (string<=? "abc" "abd")   #t]
            [assert (string<=? "abc" "abc")   #t]
            [assert (string<=? "abc" "abcd")  #t]
            [assert (string<=? "def" "abc")   #f]

            [assert (string-ci<=? "abc" "abd")  #t]
            [assert (string-ci<=? "ABC" "abd")  #t]
            [assert (string-ci<=? "abc" "ABD")  #t]
            [assert (string-ci<=? "abc" "abc")  #t]
            [assert (string-ci<=? "abc" "ABC")  #t]
            [assert (string-ci<=? "ABC" "abc")  #t]
            [assert (string-ci<=? "abc" "abcd") #t]
            [assert (string-ci<=? "ABC" "abcd") #t]
            [assert (string-ci<=? "abc" "ABCD") #t]
            [assert (string-ci<=? "def" "abc")  #f]
            [assert (string-ci<=? "DEF" "abc")  #f]
            [assert (string-ci<=? "def" "ABC")  #f]

            [assert (string>=? "abc" "abd")  #f]
            [assert (string>=? "abc" "abc")  #t]
            [assert (string>=? "abc" "abcd")  #f]
            [assert (string>=? "def" "abc")  #t]

            [assert (string-ci>=? "abc" "abd")   #f]
            [assert (string-ci>=? "ABC" "abd")   #f]
            [assert (string-ci>=? "abc" "ABD")   #f]
            [assert (string-ci>=? "abc" "abc")   #t]
            [assert (string-ci>=? "ABC" "abc")   #t]
            [assert (string-ci>=? "abc" "ABC")   #t]
            [assert (string-ci>=? "abc" "abcd")  #f]
            [assert (string-ci>=? "ABC" "abcd")  #f]
            [assert (string-ci>=? "abc" "ABCD")  #f]
            [assert (string-ci>=? "def" "abc")   #t]
            [assert (string-ci>=? "DEF" "abc")   #t]
            [assert (string-ci>=? "def" "ABC")   #t]
))

